config/routes.rb
Tweeter::Application.routes.draw do
  root "tweets#index"

  resources :tweets, only: [:new, :create]
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @query = params[:query]

    @tweets = Tweet.order('created_at DESC')
    if @query.present?
      @tweets = @tweets.where('body like ?', "%#{@query}%")
    end
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    if @tweet.save
      flash[:notice] = "Tweet created!"
      redirect_to root_url
    else
      render 'new'
    end
  end

  private
  def tweet_params
    params.require(:tweet).permit(:author, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tweeter</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= notice %>

  <%= yield %>

</body>
</html>

app/views/tweets/index.html.erb
<h1>Tweeter</h1>

<%= link_to "Post a Tweet", new_tweet_path %>
<br>
<%= form_tag root_path, method: :get do %>
  <%= text_field_tag :query, @query, placeholder: 'Search' %>
  <%= submit_tag "Search" %>
<% end %>
<br>

<% @tweets.each do |tweet| %>
  <div>
    <%= highlight (tweet.body || ""), @query %>
    - <%= tweet.created_at %>
    by <strong><%= tweet.author %></strong>
  </div>
<% end %>

app/views/tweets/new.html.erb
<h1>Post a New Tweet</h1>

<%= form_for @tweet do |f| %>
  <div>
    <%= f.label :author, "Your Name" %>
    <%= f.text_field :author %>
  </div>
  <div>
    <%= f.label :body, "Your Message" %>
    <%= f.text_field :body %>
  </div>
  <div>
    <%= f.submit "Post Tweet" %>
  </div>
<% end %>